### ISSUE TITLE
Implicit type casting in the VAD example

### ISSUE THREAD

**Issue by shaniaki** [nandohca/kista#1]
In the outputs of the `ACFAveraging_fun` function of the VAD example(s) an implicit conversion from `Word32` to `short` is performed which is not documented.
The interface to the invoked `acf_averaging` function expects arrays of `Word32` data type for the outputs however the result of the computation are assigned to elements of a `L_av_t` type for communication which packs `short` values.
Is this behavior safe and intended? If yes, it is better to be documented in the code.

**Comment by nandohca** [comment]
Dear Hosein,

First, just for the observation. In a recent commit i have just added the following comment close to the call to the acf_averaging function within the wrapper function:

```
    // Note: there is an implicit conversion from Word32 array (acf_averaging prototype)
    //       the short array in this wrapper function, which enables the match to the
    //       short array declared at the corresponding output edges (E1 and E2)
    //       The conversion does not produces any change of the VAD functionality,
    //       since the outputs are flags, result of the voice detection (or not),
    //       and only the LSB is used actually.
    //       Thanks Hosein for the observation!
```
